name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloobit:
    path: ../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  ioc_container: ^0.7.0

dev_dependencies:
  austerity: 0.0.9-beta
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
