name: bloobit
description: State management, as simple as it gets. Inspired by BloC, but stripped right back.
version: 0.0.2-beta
repository: https://github.com/MelbourneDeveloper/bloobit

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^4.17.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
