name: bloobit
description: State management, as simple as it gets. Inspired by BloC, but stripped right back.
version: 1.0.4-beta
repository: https://github.com/MelbourneDeveloper/bloobit

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  austerity: ^0.0.10-beta
  dart_code_metrics: ^5.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  ioc_container: ^1.0.8

flutter:
